# Generated by Django 5.2.5 on 2025-11-18 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegrationpermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-24 15:57:11.882540'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userintegrationpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
