# Generated by Django 5.2.5 on 2025-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
