# Generated by Django 5.2.5 on 2025-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='extra_config',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='username',
        ),
        migrations.AddField(
            model_name='integration',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
