# Generated by Django 5.2.5 on 2025-11-29 00:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_rename_extra_config_integration_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='type', unique=True),
        ),
    ]
