# Generated by Django 5.2.5 on 2025-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_integration_slug'),
    ]

    operations = [

        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('tenable_sc', 'Tenable.SC'), ('invicti', 'Invicti')], default='tenable_sc', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='integration',
            name='type',
        ),  
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('name', 'provider')},
        ),
    ]
